plugins {
    id 'java'
    id 'maven-publish'
    id 'architectury-plugin' version '3.5-SNAPSHOT'
    id 'dev.architectury.loom' version '1.17-SNAPSHOT'
    id 'com.gradleup.shadow' version '9.3.0+' apply false
}

architectury {
    common("fabric", "neoforge")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
}

allprojects {
    apply plugin: 'architectury-plugin'
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'maven-publish'

    group = project.maven_group
    version = project.mod_version

    repositories {
        mavenCentral()
        maven { url = uri("https://maven.fabricmc.net/") }
        maven { url = uri("https://maven.neoforged.net/releases/") }
        maven { url = uri("https://maven.architectury.dev/") }
        maven { url = uri("https://api.modrinth.com/maven") }
        maven { url = uri("https://maven.terraformersmc.com/releases")}
    }

    var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
        var properties = [
                mod_id                          : project.mod_id,
                mod_version                     : project.mod_version,
                mod_name                        : project.mod_name,
                mod_description                 : project.mod_description,
                mod_authors                     : project.mod_authors,
                mod_credits                     : project.mod_credits,
                mod_license                     : project.mod_license,
                mod_homepage                    : project.mod_homepage,
                mod_sources                     : project.mod_sources,
                mod_issues_page                 : project.mod_issues_page,
                maven_group                     : project.maven_group,
                archive_base_name               : project.archive_base_name,

                minecraft_version               : project.minecraft_version,

                neoforge_loader_version         : project.neoforge_loader_version,
                neoforge_version                : project.neoforge_version,
                neoforge_minecraft_version_range: project.neoforge_minecraft_version_range,
                neoforge_loader_version_range   : project.neoforge_loader_version_range,
                neoforge_version_range          : project.neoforge_version_range,

                fabric_loader_version           : project.fabric_loader_version,
                fabric_api_version              : project.fabric_api_version,
                fabric_minecraft_version_range  : project.fabric_minecraft_version_range,
                fabric_loader_version_range     : project.fabric_loader_version_range,
                fabric_api_version_range        : project.fabric_api_version_range,
        ]
        inputs.properties properties
        expand properties
        from 'src/main/templates'
        into 'build/generated/sources/mod-metadata'
    }
    sourceSets.main.resources.srcDir generateModMetadata
    processResources.dependsOn generateModMetadata
}

subprojects {
    if (project.name in ['fabric', 'neoforge']) {
        apply plugin: 'com.gradleup.shadow'

        configurations {
            shadowCommon {
                canBeResolved = true
                canBeConsumed = false
            }
        }

        shadowJar {
            exclude 'architectury.common.json'

            if (project.name == 'fabric') {
                exclude 'META-INF/neoforge.mods.toml'
            } else if (project.name == 'neoforge') {
                exclude 'fabric.mod.json'
            }
            configurations = [project.configurations.shadowCommon]
            archiveClassifier = ''
        }

        tasks.named('shadowJar') {
            archiveFileName = "${project.mod_name}-${project.mod_version}-mc${project.minecraft_version}-${project.name}-shadow.jar"
        }

        tasks.named('remapJar') {
            inputFile.set(shadowJar.archiveFile)
            dependsOn shadowJar
            archiveClassifier = null
            archiveFileName = "${project.mod_name}-${project.mod_version}-mc${project.minecraft_version}-${project.name}.jar"
        }
    }

    sourceSets.main.resources.srcDir rootProject.file('build/generated/sources/mod-metadata')

    processResources {
        dependsOn rootProject.tasks.named('generateModMetadata')
        from rootProject.file('src/main/resources')
        if (project.name == 'fabric') {
            exclude 'META-INF/neoforge.mods.toml'
        } else if (project.name == 'neoforge') {
            exclude 'fabric.mod.json'
        }
    }
}