org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
mod_id=copperskin
mod_version=0.1.0
mod_name=CopperSkin
mod_description=About Name your Copper Golem after a player to make it wear their skin.
mod_authors=ming_yuan
mod_credits=
mod_license=
mod_homepage=https://github.com/mingyuan3709/CopperSkin
mod_sources=https://github.com/mingyuan3709/CopperSkin
mod_issues_page=https://github.com/mingyuan3709/CopperSkin/issues
maven_group=ink.mingyuan.copperskin
archive_base_name=copperskin
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=1.21.11

# Loaders version
neoforge_loader_version=4
neoforge_version=21.11.42
fabric_loader_version=0.19.3
fabric_api_version=0.141.4+1.21.11

# Dependencies version
fabric_mod_menu_version=17.0.0-beta.1

# Version range used in mod metadata
neoforge_minecraft_version_range=[1.21.1,)
neoforge_loader_version_range=[4,)
neoforge_version_range=[1.21.1,)

fabric_minecraft_version_range=>=1.21.11
fabric_loader_version_range=>=0.18
fabric_api_version_range=*
