architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom(common)
    runtimeClasspath.extendsFrom(common)
    developmentNeoForge.extendsFrom(common)
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"
    mappings loom.officialMojangMappings()
    common(project(path: ":", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":", configuration: "transformProductionNeoForge")) { transitive false }
}